### ISSUE TITLE
A typo in MSSRPG_Common_Stats_Pawns_General.xml

### ISSUE THREAD

**Issue by Deon-DF** [MrSamuelStreamer/RPGFantasyFlavourMod#22]
Closing tag </AnimalsLearningFactor.description> doesn't have a dot (it's written as </AnimalsLearningFactordescription>) which doesn't match the opening tag.

**Comment by feldoh** [comment]
fixed in f7210097a44b43ea5adfa06741434c38cde1d3a3
will be included in the next workshop release 🙇
