### ISSUE TITLE
Cry Babies and Necromancy, a Deadly Combo

### ISSUE THREAD

**Issue by MrSamuelStreamer** [MrSamuelStreamer/RPGFantasyFlavourMod#44]
Beloved character in the series died and now everyone is quick to point out that Necromancy is an option without considering the balance rammifications.

Couple of balance ideas I had for solving this issue:

**Animal resurrection only**
Pros:
- Solves balance issue
Cons:
- Doesn't silence cry babies
- A bit boring

**Harsher resurrect costs**
Pros:
- Shuts up cry babies
Cons:
- Balance can still be mitigated given the extensive tools in VPE
- Would most likely end up destroying another beloved character through nerfs

**Alternative resurrection consequences**
Pros:
- Shuts up cry babies
- Balance against the dead person, so still a net positive
Cons:
- Still overpowered
- More work

**Comment by MrSamuelStreamer** [comment]
Re **Alternative resurrection consequences**, this could include any of the following:

- Necromancer takes on random trait from the resurrected
- Necromancer goes unconcious depending on how long the body has been down for
- Resurrected gets genes scrambled
- Resurrected gets manky limbs (fleshcrafted limbs from Alpha Genes, gives sickness, rejection etc, need to be operated)
- Resurrected loses limbs
- Resurected changes traits

**Comment by feldoh** [comment]
Also:
* Necromancer finger severance causes "soul-sever" which prevents the limb EVER being replaced, if you try it'll just fall off.
* What if it wasn't the finger or the heart as I've seen suggested but a _random_ bodypart. You might res the pawn at the cost of a finger, or an arm... or a brain. This doesn't make it actually unusable but vastly reduces its desirability. Life potions (full res) do exist in this scenario albeit very rare so you can have the necro bring back a more important party member then put them on ice trusting that their party will hunt for a ressurect potion to bring them back.

**Comment by davidturner** [comment]
Just going to throw this in as another possible option, aimed primarily at colonist resurrection:

- Resurrected colonist receives the Blood Rot medical condition, meaning their return is limited to their ability to be tended.

This would add a cost in terms of medicine, tending time, and could cause all sorts of colony sadness should a colonist succumb to the Rot and die a second time.

If the "Cure Blood Rot" surgery is still available in game, I'd also remove that to avoid one of the ways of gaming this penalty.

**Comment by MrSamuelStreamer** [comment]
Resolved in recent VE Patch
