### ISSUE TITLE
Missing/Broken Translations

### ISSUE THREAD

**Issue by MrSamuelStreamer** [MrSamuelStreamer/RPGFantasyFlavourMod#48]
These all need fixing, adding, or renaming in some capacity, feel free to suggest new renames!

Psychic Bonding (_Biotech_) - Magic Bonding

Innate Psyline Gene (_Alpha Genes_) - Innate Magic Gene
Psychic Camoflage (_Alpha Genes_) - Magical Camoflage
Psychic Remapping (_Alpha Genes_) - Magical Inversion
Psychic Insanity (_Alpha Genes_) - Magical Insanity
Psychic Sight (_Alpha Genes_) - Magical Sight

Heat Dispersal (_Integrated Genes_) - Arcane Dispersal (DO NOT shorten and remove 'Arcane')
Super Heat Dispersal (_Integrated Genes_) - Super Arcane Dispersal (DO NOT shorten and remove 'Arcane')
Heat Retention (_Integrated Genes_) - Arcane Retention 
Super Heat Retention (_Integrated Genes_) - Super Arcane Retention 
Archotech Attunement (_Integrated Genes_) - Extreme Magical Attunement

Natural Psychic (_Big and Small Genes_) - Nature Attuned

Natural Psylink (_VE Archon_) - Innate Magic Gene (Duplicate with Alpha Gene)
Transcendent (_VE Archon_) - Interdimensional Magic
Weak Entropic Capacity (_VE Archon_) - Weak Magical Capacity
High Entropic Capacity (_VE Archon_) - High Magical Capacity
Extreme Entropic Capacity (_VE Archon_) - Extreme Magical Capacity
Extreme Psy-sensitive (_VE Archon_) - Extremely Magic Sensitive

**Comment by feldoh** [comment]
![image](https://github.com/MrSamuelStreamer/RPGFantasyFlavourMod/assets/3587179/736d83de-c4e1-4fca-9d27-e7d150bb4468)
