### ISSUE TITLE
Wizard Tales Suggestion: Sorting Hat

### ISSUE THREAD

**Issue by ENDRI4N** [MrSamuelStreamer/RPGFantasyFlavourMod#50]
We all know that children born in a colony get nothing special for that childhood background, nothing to help improve their skills in preparation for adulthood, unlike children that come in from outside the colony.

However, in a mod pack that rapidly accelerates aging, especially for children, that will leave them woefully lacking in the skills department when they hit adulthood.

What if, in this wizarding-themed mod pack, you had a special building/furniture/spawnable NPC that could be interacted with by a child, and it would "sort" them, either randomly or based on their traits or on their genes, into a specific wizarding "house"? And then they would receive a Childhood Backstory relevant to that house, complete with skill buffs.

**Example:**
Baby Bonfire (Bonnie to her friends), child of Wildfire and Rambunkulus/Burt (who's the father? _It Is A Mystery_), is made to interact with the "Sorting Hat"-type object/NPC. Upon interacting, she might receive the "Wildfire House" Childhood Backstory, giving them bonuses in skills that Wildfire (as founder of the house) has as passions or is particularly skilled at, or perhaps it would be a more generalized "Phoenix House" with fire- or phoenix-related skills like Cooking, Healing, Intellectual, and so on.

**Comment by MrSamuelStreamer** [comment]
Completed by the one and only Dexter Feldoh
