### ISSUE TITLE
add the wizard robes from adventure time

### ISSUE THREAD

**Issue by BigSmoke811** [MrSamuelStreamer/RPGFantasyFlavourMod#52]
![wizardrobe](https://github.com/MrSamuelStreamer/RPGFantasyFlavourMod/assets/161972430/5b55647e-a956-4d4c-97b9-5e4da947c899)
it fits the theme of the wizards growing stronger after tons of meditation

**Comment by MrSamuelStreamer** [comment]
Not familiar with the original source and already worried about the massive amount of robes already in the game, but will shelve for now and come back if I decide to make more standalone gear!
