### ISSUE TITLE
Mythical Keyblades as relics or rare melee weapons!

### ISSUE THREAD

**Issue by NovaCeltic** [MrSamuelStreamer/RPGFantasyFlavourMod#54]
https://steamcommunity.com/sharedfiles/filedetails/?id=2386352416

an old mod that hasn't been updated, but perhaps retextures for melee weapons, if its not too much trouble Mr.Streamer.

Many Thanks, Big Gay At Large.

**Comment by MrSamuelStreamer** [comment]
Cool mod, but definitely more suited to someone like Mlie resurrecting the original and I have no idea about the source material, sorry!
