### ISSUE TITLE
Prisoner gathering areas

### ISSUE THREAD

**Issue by XacBlook** [MrSamuelStreamer/RPGFantasyFlavourMod#55]
so, im aware that the force to work mod thing is installed, which technically might make this semi irrelevent, but it would be great to be able to have a prison with a common eating space for the prisoners, it keeps moral up for the prisoners since they can get mood buffs from dining halls as well as their cell, and it can help with roleplay and stuff

**Comment by XacBlook** [comment]
maybe make it to where prisoners can also ponder orbs for meditating so that they can still work on levels while recruiting

**Comment by MrSamuelStreamer** [comment]
Possible to achieve with the Prison Commons mod already
https://steamcommunity.com/sharedfiles/filedetails/?id=2898000489
