### ISSUE TITLE
Arcane Trader Bug

### ISSUE THREAD

**Issue by MrSamuelStreamer** [MrSamuelStreamer/RPGFantasyFlavourMod#63]
Arcane Traders have nothing for sale other than cloth or amber

**Comment by feldoh** [comment]
![image](https://github.com/MrSamuelStreamer/RPGFantasyFlavourMod/assets/3587179/f6fe69f4-e70e-4487-98e1-d82c7508a767)
Looks like it must be a conflict of some kind; anything in logs?

**Comment by feldoh** [comment]
Maybe whatever mod is adding amber to them is removing the rest of the options

**Comment by feldoh** [comment]
I searched the amber and found something. I think this might actually just be confusion the RPG arcane trader is not the same as the arcane goods merchant from `Medieval Overhaul: Arcane Archaeologists` (package: `Ogam.MedievalOverhaul.ArcaneArchaeologists`) which is in fact defined as a dedicated trader that only sells amber and cloth

![image](https://github.com/MrSamuelStreamer/RPGFantasyFlavourMod/assets/3587179/c6f04761-39dc-46a3-9fd8-a1929f834d73)

could patch in extra stuff to make it sell more if you like

**Comment by feldoh** [comment]
With commonality 3 it's 3x more likely compared to the RPG ones

**Comment by MrSamuelStreamer** [comment]
Yeah, looked into myself afterwards, we definitely need to patch that caravan because its far too frequent, unless we rebalance what they sell

**Comment by MrSamuelStreamer** [comment]
Update, turns out the arcane archaeologists faction, which is the only friendly faction in the game, only has access to the "Arcane Caravan" - no bulk goods trader, no RPG flavour pack caravans. Ideally needs fixing asap otherwise eltex flow will be slow

![image](https://github.com/MrSamuelStreamer/RPGFantasyFlavourMod/assets/59952292/ca4d90e5-edc0-426f-bcab-9dbea44e5508)
